version: '3.8'

services:
  # PostgreSQL para tu backend (base de datos separada de Evolution API)
  postgres_backend:
    image: postgres:15-alpine
    container_name: whatsapp_saas_db
    restart: always
    ports:
      - '5433:5432'  # Puerto 5433 para no conflictuar con el PostgreSQL de Evolution
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatsapp_saas
    volumes:
      - postgres_backend_data:/var/lib/postgresql/data
    networks:
      - whatsapp_backend_network

  # Redis compartido - comentado porque usaremos el de Evolution API
  # redis_backend:
  #   image: redis:7-alpine
  #   container_name: whatsapp_saas_redis
  #   restart: always
  #   ports:
  #     - '6380:6379'  # Puerto diferente si necesitas tu propio Redis
  #   volumes:
  #     - redis_backend_data:/data
  #   networks:
  #     - whatsapp_backend_network

  # Evolution API ahora corre externamente en el puerto 8080
  # desde el repositorio clonado de evolution-api

volumes:
  postgres_backend_data:
  # redis_backend_data:

networks:
  whatsapp_backend_network:
    driver: bridge